sudo: required
services:
  - docker

before_install:
  - docker build -t oluwandy/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true oluwandy/react-test npm run test

after_success:
  - docker build -t toks122/multi-client ./client
  - docker build -t toks122/multi-nginx ./nginx
  - docker build -t toks122/multi-server ./server
  - docker build -t toks122/multi-worker ./worker
#docker login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# push image created to docker hub
  - docker push toks122/multi-client
  - docker push toks122/multi-nginx
  - docker push toks122/multi-server
  - docker push toks122/multi-worker
